#mybatis日志
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/blossom/ggkt/user/mapper/xml/*.xml
# 服务端口
server:
    port: 8305

spring:
    # 服务名
    application:
        name: service-wechat
    # nacos服务地址
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    # mysql数据库连接
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/glkt_wechat?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        password: root
        username: root
    #返回json的全局时间格式
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # 环境设置：dev、test、prod
    profiles:
        active: dev

#公众号id和秘钥
wechat:
# 硅谷课堂微信公众平台appId
    #mpAppId: wx09f201e9013e81d8
#我的订阅号
    mpAppId: wx1fab4e306bed9d96
# 硅谷课堂微信公众平台api秘钥
    #wechatmpAppSecret: 6c999765c12c51850d28055e8b6e2eda
#我的订阅号
    wechatmpAppSecret: 67e533f1219a6104004605780b392a05
