#mybatis日志
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/blossom/ggkt/activity/mapper/xml/*.xml
# 服务端口
server:
    port: 8303

spring:
    # 服务名
    application:
        name: service-activity
    # nacos服务地址
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    # mysql数据库连接
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/glkt_activity?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        password: root
        username: root
    #返回json的全局时间格式
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # 环境设置：dev、test、prod
    profiles:
        active: dev
